### ISSUE TITLE
warning: implicit declaration of function uriIsHostSetA

### ISSUE THREAD

**Issue by nukleus** [petere/pguri#2]
uri.c: In function ‘uri_path’:
    uri.c:238:2: warning: implicit declaration of function ‘uriIsHostSetA’ [-Wimplicit-function-declaration]
        if (uri.absolutePath || (uriIsHostSetA(&uri) && uri.pathHead))
                                 ^

uriparser seems to only define uriIsHostSet, without the 'A', typo?

**Comment by petere** [comment]
No, it's correct that way.  If I change it, I get a linker error.
